blank_issues_enabled: false
contact_links:
  - name: ElectronicCats
    about: Try to see if ther is an answer for yoru questions before you create a new issue.
    url: https://github.com/ElectronicCats/mpu6050/issues